
package org.oasis_open.docs.wsrf.rw_2;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-04-04T00:56:48.764+02:00
 * Generated source version: 3.1.10
 */

public class ResourceUnknownFault extends Exception {
}
